server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatiCfg.xml  #mybatis\u6240\u5728\u8DEF\u5F84
  type-aliases-package: com.macongcong.entity #entity\u522B\u540D\u7C7B
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml #mapper\u6620\u5C04\u6587\u4EF6

spring:
  application:
    name: micoreservicecloud-dept
  #配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/1703e
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client: #\u5BA2\u6237\u7AEF\u6CE8\u518C\u8FDBeureka\u670D\u52A1\u5217\u8868\u5185
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: MICORESERVICECLOUD-DEPT   #\u81EA\u5B9A\u4E49hystrix\u76F8\u5173\u7684\u670D\u52A1\u540D\u79F0\u4FE1\u606F
    prefer-ip-address: true     #\u8BBF\u95EE\u8DEF\u5F84\u53EF\u4EE5\u663E\u793AIP\u5730\u5740

info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
